Repository Mirim-Study/Algorithm, pull requests merged in 2020-10, with the labels that each got.

#170 level02.올바른 괄호
  programmers/난이도별/level02.올바른_괄호/SSSOy.java
Labels: JAVA

#158 level02.NULL_처리하기
  programmers/난이도별/level02.NULL_처리하기/sokkanji.sql
Labels: MySQL

#162 level01.가운데_글자_가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/JiaLee0707.c
Labels: C

#163 level01.두_정수_사이의_합
  programmers/난이도별/level01.두_정수_사이의_합/JiaLee0707.c
Labels: C

#164 level01.문자열_내림차순으로_배치하기
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/JiaLee0707.c
Labels: C

#169 level01.수박수박수박수박수박수
  programmers/난이도별/level01.수박수박수박수박수박수/JiaLee0707.c
Labels: C

#171 level01.약수의_합
  programmers/난이도별/level01.약수의_합/JiaLee0707.c
Labels: C

#167 level01.문자열 내림차순으로 배치하기
  programmers/난이도별/level01.문자열_내림차순으로_배치하기/SSSOy.java
Labels: JAVA

#168 level02.중성화 여부 파악하기
  programmers/난이도별/level02.중성화_여부_파악하기/SSSOy.sql
Labels: JAVA

#172 level02.고양이와 개는 몇 마리 있을까
  programmers/난이도별/level02.고양이와_개는_몇_마리_있을까/SSSOy.sql
Labels: OracleSQL

#174 level03.오랜 기간 보호한 동물(1)
  programmers/난이도별/level03.오랜_기간_보호한_동물(1)/areumsheep.sql
Labels: OracleSQL

#176 level01.문자열 내 마음대로 정렬하기
  programmers/난이도별/level01.문자열_내_마음대로_정렬하기/SSSOy.java
Labels: JAVA

#175 level02.DATETIME에서 DATE로 형 변환
  programmers/난이도별/level02.DATETIME에서_DATE로_형_변환/SSSOy.sql
Labels: OracleSQL

#177 level01.가운데 글자 가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/SSSOy.java
Labels: JAVA

#179 level02.땅따먹기
  programmers/난이도별/level02.땅따먹기/areumsheep.js
Labels: JavaScript

#173 level01.짝수와_홀수
  programmers/난이도별/level01.짝수와_홀수/JiaLee0707.c
Labels: C

#178 level02.H-Index
  programmers/난이도별/level02.H-Index/SSSOy.java
Labels: JAVA

#180 level01.소수 찾기
  programmers/난이도별/level01.소수_찾기/SSSOy.java
Labels: JAVA

#181 level01.어린 동물 찾기
  programmers/난이도별/level01.어린_동물_찾기/SSSOy.sql
Labels: OracleSQL

#182 level01.체육복
  programmers/난이도별/level01.체육복/SSSOy.java
Labels: JAVA

#183 level02.입양 시각 구하기(1)
  programmers/난이도별/level02.입양_시각_구하기(1)/SSSOy.sql
Labels: OracleSQL

#184 level03.오랜 기간 보관한 동물(2)
  programmers/난이도별/level03.오랜_기간_보호한_동물(2)/SSSOy.sql
Labels: OracleSQL
