Repository Mirim-Study/Algorithm, pull requests merged in 2020-11, with the labels that each got.

#186 level03. 오랜 기간 보호한 동물(2)
  programmers/난이도별/level03.오랜_기간_보호한_동물(2)/areumsheep.sql
Labels: MySQL

#185 level01.문자열_다루기_기본
  programmers/난이도별/level01.문자열_다루기_기본/yeeun.js
Labels: JavaScript

#187 level01.서울에서 김서방 찾기
  programmers/난이도별/level01.서울에서_김서방_찾기/SSSOy.py
Labels: Python

#188 level01.수박수박수박수박수박수?
  programmers/난이도별/level01.수박수박수박수박수박수/SSSOy.py
Labels: Python

#189 level01.시저 암호
  programmers/난이도별/level01.시저_암호/SSSOy.py
Labels: Python

#192 level01.약수의 합
  programmers/난이도별/level01.약수의_합/SSSOy.py
Labels: Python

#190 level01.모의고사
  programmers/난이도별/level01.모의고사/SSSOy.py
Labels: Python

#191 level01.제일 작은 수 제거하기
  programmers/난이도별/level01.제일_작은_수_제거하기/SSSOy.py
Labels: Python

#193 level01.K번째수
  programmers/난이도별/level01.K번째수/SSSOy.py
Labels: Python

#195 level01.자연수 뒤집어 배열로 만들기
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/SSSOy.py
Labels: Python

#196 level01.이상한 문자 만들기
  programmers/난이도별/level01.이상한_문자_만들기/SSSOy.py
Labels: Python

#198 level01. 짝수와 홀수
  programmers/난이도별/level01.짝수와_홀수/areumsheep.java
Labels: JAVA
