Repository Mirim-Study/Algorithm, pull requests merged in 2020-08, with the labels that each got.

#2 level01. 약수의 합
  programmers/난이도별/level01.약수의_합/areum.js
Labels: JavaScript

#4 level01.K번째수
  programmers/난이도별/level01.K번째수/yoojinhee03.java
Labels: JAVA

#8 프로그래머스 사이트 추가
  programmers/README.md
  programmers/난이도별/2016년.js
Labels: 건의사항

#6 Create level01.약수의_합/yoojinhee03.java
  programmers/난이도별/level01.약수의_합/yoojinhee03.java
Labels: JAVA

#5 Create level01.문자열을 정수로 바꾸기/yoojinhee03.java
  programmers/난이도별/level01.문자열을 정수로 바꾸기/yoojinhee03.java
Labels: JAVA

#9 메인화면 README.md 수정
  README.md
Labels: 건의사항

#12 Create level01.약수의_합/heena01.py
  programmers/난이도별/level01.약수의_합/heena01.py
Labels: Python

#15 level01.2016년
  programmers/난이도별/level01.2016년/yoojinhee03.java
Labels: JAVA

#17 level01.평균값 구하기
  programmers/난이도별/level01.평균값_구하기/yoojinhee03.java
Labels: JAVA

#18 level01.x만큼 간격이 있는 n개의 숫자
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/yoojinhee03.java
Labels: JAVA

#19 level01.2016년
  programmers/난이도별/level01.2016년/heena.java
Labels: JAVA

#20 level01.정수 내림차순으로 정리하기
  programmers/난이도별/level01.정수_내림차순으로_배치하기/areum.js
Labels: JavaScript

#21 level01.자연수 뒤집어 배열로 만들기
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/areum.js
Labels: JavaScript

#23 level01.약수의_합/wander0220.js & READ.md에 저 추가함.
  README.md
  programmers/난이도별/level01.약수의_합/wander0220.js
Labels: JavaScript

#24 level01.정수 제곱근 판별
  programmers/난이도별/level01.정수_제곱근_판별/yoojinhee03.java
  programmers/난이도별/level01.평균_구하기/yoojinhee03.java
Labels: JAVA

#26 level01.동물의 아이디와 이름
  programmers/난이도별/level01.동물의_아이디와_이름/heena.sql
Labels: SQL

#31 level01.가운데_글자_가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/suhyeon.java
  programmers/난이도별/level01.아픈_동물_찾기/suhyeon.sql
Labels: JAVA

#35 level01.수박수박수박수박수박수
  programmers/난이도별/level01.수박수박수박수박수박수/yoojinhee03.java
Labels: JAVA

#29 level01.가운데_글자_가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/yeeun.js
Labels: JavaScript

#33 level01.약수의 합
  programmers/난이도별/level01.약수의_합/pppeum62.java
Labels: JAVA

#36 level01.최대공약수와 최소공배수
  programmers/난이도별/level01.최대공약수와_최소공배수/areum.js
Labels: JavaScript

#28 level01.하샤드 수
  programmers/난이도별/level01.하샤드_수/areum.js
Labels: JavaScript

#27 level01.자릿수 더하기
  programmers/난이도별/level01.자릿수_더하기/areum.js
Labels: JavaScript

#37 level01.수박수박수박수박수박수?
  programmers/난이도별/level01.수박수박수박수박수박수?/Suhyeon.java
Labels: JAVA

#39 level01.이상한 문자 만들기
  programmers/난이도별/level01.이상한_문자_만들기/areum.js
Labels: JavaScript

#30 level01.모의고사
  programmers/난이도별/level01.모의고사/SSSOy.java
Labels: JAVA

#41 level01.두 정수 사이의 합
  programmers/난이도별/level01.두_정수_사이의_합/pppeum62.js
Labels: JavaScript

#38 level01.소수 찾기
  programmers/난이도별/level01.소수_찾기/pppeum62.java
Labels: JAVA

#42 level01.두_정수_사이의_합
  programmers/난이도별/level01.두_정수_사이의_합/yeeun.c
Labels: C

#46 Update README.md
  README.md
Labels: 건의사항

#43 level01.문자열_내_p와_y의_개수
  programmers/난이도별/level01.문자열_내_p와_y의_개수/yeeun.js
Labels: JavaScript

#44 level01.문자열 내 p와 y의 개수
  programmers/난이도별/level01.문자열_내_p와_y의_개수/suhyeon.js
Labels: JavaScript, 도움요청

#45 level01.서울에서 김서방 찾기
  programmers/난이도별/level01.서울에서_김서방_찾기/pppeum62.js
Labels: JavaScript

#47 level01.시저암호
  programmers/난이도별/level01.시저암호/areum.js
Labels: JavaScript

#49 level01.아픈 동물 찾기
  programmers/난이도별/level01.아픈_동물_찾기/pppeum62.sql
Labels: SQL

#40 level01.같은 숫자는 싫어
  programmers/난이도별/level01.같은_숫자는_싫어/pppeum62.js
Labels: JavaScript
