Repository Mirim-Study/Algorithm, pull requests merged in 2021-09, with the labels that each got.

#345 level01.부족한 금액 계산하기
  programmers/난이도별/level01.부족한_금액_계산하기/SSSOy.java
Labels: JAVA

#346 level01.상호 평가
  programmers/난이도별/level01.상호_평가/SSSOy.java
Labels: JAVA

#347 level01.부족한 금액 계산하기
  programmers/난이도별/level01.부족한_금액_계산하기/pppeum62.js
Labels: JavaScript

#348 level01.상호평가
  programmers/난이도별/level01.상호평가/pppeum62.js
Labels: JavaScript

#355 level01. 짝수와_홀수
  programmers/난이도별/level01.짝수와_홀수/Moon-Hyekyung.js
Labels: JavaScript

#357 level01.없는 숫자 더하기
  programmers/난이도별/level01.없는_숫자_더하기/pppeum62.js
Labels: JavaScript

#354 level01. 2016년
  programmers/난이도별/level01.2016년/Moon-Hyekyung.js
Labels: JavaScript

#356 level01. 음양_더하기
  programmers/난이도별/level01.음양_더하기/Moon-Hyekyung.js
Labels: JavaScript

#358 level01.없는 숫자 더하기
  programmers/난이도별/level01.없는_숫자_더하기/SSSOy.java
Labels: JAVA

#352 level01.복서 정렬하기
  programmers/난이도별/level01.복서_정렬하기/SSSOy.java
Labels: JAVA

#351 level01.직업군 추천하기
  programmers/난이도별/level01.직업군_추천하기/SSSOy.java
Labels: JAVA

#359 level 01. 핸드폰 번호 가리기
  programmers/난이도별/level01.핸드폰_번호_가리기/Moon-Hyekyung.js
Labels: JavaScript

#365 level01.3진법 뒤집기
  programmers/난이도별/level01.3진법_뒤집기/pppeum62.js
Labels: JavaScript

#360 level01.시저 암호
  programmers/난이도별/level01.시저_암호/pppeum62.js
Labels: JavaScript

#366 level01. x만큼 간격이 있는 n개의 숫자
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/Moon-Hyekyung.js
Labels: JavaScript

#361 level01.소수 만들기
  programmers/난이도별/level01.소수_만들기/pppeum62.js
Labels: JavaScript

#368 lever01. 평균 구하기
  programmers/난이도별/level01.평균_구하기/Moon-Hyekyung.js
Labels: JavaScript

#374 level 01. 3진법 뒤집기
  programmers/난이도별/level01.3진법_뒤집기/Moon-Hyekyung.js
Labels: JavaScript

#364 level01. 문자열 다루기 기본
  programmers/난이도별/level01.문자열_다루기_기본/pppeum62.js
Labels: JavaScript

#367 level03.헤비 유저가 소유한 장소
  programmers/난이도별/level03.헤비_유저가_소유한_장소/SSSOy.sql
Labels: MySQL

#363 level02.최솟값 만들기
  programmers/난이도별/level02.최솟값_만들기/SSSOy.java
Labels: JAVA

#372 level 01. 수박수박수박수박수박수?
  programmers/난이도별/level01.수박수박수박수박수박수/Moon-Hyekyung.js
Labels: JavaScript

#375 level 01. 하샤드 수
  programmers/난이도별/level01.하샤드_수/Moon-Hyekyung.js
Labels: JavaScript

#371 level 01. 콜라츠 추측
  programmers/난이도별/level01.콜라츠_추측/Moon-Hyekyung.js
Labels: JavaScript

#373 level01. 문자열을 정수로 바꾸기
  programmers/난이도별/level01.문자열을_정수로_바꾸기/Moon-Hyekyung.js
Labels: JavaScript

#376 level01.K번째 수
  programmers/난이도별/level01.K번째수/pppeum62.js
Labels: JavaScript

#370 level 01. 자연수 뒤집어 배열로 만들기
  programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/Moon-Hyekyung.js
Labels: JavaScript

#342 level01.음양 더하기
  programmers/난이도별/level01.음양_더하기/areumsheep.js
Labels: JavaScript

#378 level 01. 정수 제곱근 판별
  programmers/난이도별/level01.정수_제곱근_판별/Moon-Hyekyung.js
Labels: JavaScript

#341 level01.음양 더하기
  programmers/난이도별/level01.음양_더하기/devSOWON0628.java
Labels: JAVA

#380 level01.x만큼 간격이 있는 n개의 숫자
  programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/pppeum62.java
Labels: JAVA

#381 level01.가운데 글자 가져오기
  programmers/난이도별/level01.가운데_글자_가져오기/pppeum62.java
Labels: JAVA
