Repository Mirim-Study/Algorithm, pull requests merged in 2022-06, with the labels that each got.

#486 level01.키패드 누르기
  programmers/난이도별/level01.키패드_누르기/sokkanji.js
Labels: JavaScript

#482 level02.타겟 넘버
  programmers/난이도별/level02.타겟_넘버/JiaLee0707.js
Labels: JavaScript, 추천 문제

#488 25205번: 경로당펑크 2077
  baekjoon/25205.경로당펑크_2077/pppeum62.java
Labels: JAVA
